version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: taskmanager_postgres
    restart: always
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: fabriciorosa
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - postgres_password
volumes:
  pgdata:
secrets:
  postgres_password:
    file: ./postgres_password.txt
